version: "3.8"

services:
  bot:
    image: "${BOT_IMAGE_NAME}"
    container_name: "${BOT_CONTAINER_NAME}"
    stop_signal: SIGINT
    build:
      dockerfile: docker/Dockerfile.telegram-bot
      context: bot
    working_dir: "/usr/src/app/${BOT_NAME}"
    volumes:
      - ./bot:/usr/src/app/${BOT_NAME}
    command: python3 -m bot
    restart: always
    env_file:
      - ".env"
    networks:
      - bot
    profiles: ["backend-dev", "ci"]

networks:
  bot:
    driver: bridge