"""Init migration

Revision ID: 1e615f960fd5
Revises: 
Create Date: 2023-08-13 09:52:11.840761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e615f960fd5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('creator_telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('is_done', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_exist', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('role', sa.Enum('USER', 'MODERATOR', 'ADMINISTRATOR', name='role'), nullable=False),
    sa.Column('last_activity_date', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('user_agreement_acceptance_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_language', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.PrimaryKeyConstraint('telegram_user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('task')
    # ### end Alembic commands ###
