"""added_model_event

Revision ID: 5cc3a512fe51
Revises: eea4d61cf2b2
Create Date: 2023-08-21 16:22:45.288591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5cc3a512fe51'
down_revision: Union[str, None] = 'eea4d61cf2b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('type', sa.Enum('MESSAGE', 'CALLBACK_QUERY', name='eventtype'), nullable=False),
    sa.Column('occurrence_date', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('callback_data_prefix', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.ForeignKeyConstraint(['telegram_user_id'], ['user.telegram_user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    # ### end Alembic commands ###
